// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a session-mode connection (DDL, advisory locks), which the
    // transaction pooler on :6543 doesn't support. DIRECT_URL points at the
    // session pooler on :5432; fall back to DATABASE_URL if it isn't set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
